services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  TRAW\NotificationsFramework\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  TRAW\NotificationsFramework\Domain\Model\Type:
    public: true

  TRAW\NotificationsFramework\Events\Database\AfterDatabaseOperationsEventListener:
    tags:
      - name: event.listener
        event: TRAW\NotificationsFramework\Events\Database\AfterDatabaseOperationsEvent
        identifier: 'traw-notifications/database'
  TRAW\NotificationsFramework\Events\Data\NotificationJsonDataEventListener:
    tags:
      - name: event.listener
        event: TRAW\NotificationsFramework\Events\Data\NotificationJsonDataEvent
        identifier: 'traw-notifications/notifcation-json-data'

  TRAW\NotificationsFramework\OperationHandler\GetUserNotificationsOperationHandler:
    public: true
  TRAW\NotificationsFramework\OperationHandler\PatchUserNotificationsOperationHandler:
    public: true
  TRAW\NotificationsFramework\Domain\Repository\Json\NotificationRepository:
    public: true
  TRAW\NotificationsFramework\Utility\AudienceUtility:
    public: true
