services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  TRAW\NotificationsFramework\:
    resource: '../Classes/*'
  
  TRAW\NotificationsFramework\Events\Database\AfterDatabaseOperationsEventListener:
    tags:
      - name: event.listener
        event: TRAW\NotificationsFramework\Events\Database\AfterDatabaseOperationsEvent
        identifier: 'traw-notifications/database'